id: P34C4E1BA
initial_creation_type: input
source_metadata:
  title: Metrul Tendzin Gyatso Series
  language: en
  description: Texts by Metrul Tendzin Gyatso (rme sprul bstan 'dzin rgya mtsho, b.
    1968)
  volume:
    3bc598fa2da04e80a77a5cca01f73f70:
      title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
        the Lives of Animals'
      parent: Saving Lives
created_at: '2022-03-01T00:45:41.022804'
last_modified_at: '2022-03-01T00:45:41.022811'
